### ISSUE TITLE
3D volume rendering not working

### ISSUE THREAD

**Issue by mcyc** [glue-viz/glue-vispy-viewers#146]
I received the following error messages when trying to 3D volume render a data cube. I'm currently running OS X El Capitan (v. 10.11.5) on my laptop, and as far as I can tell, all of my python libraries are currently up to date. I have no problem viewing the same data cube with glue image viewer.

`
2016-05-17 16:49:32.288 python[2048:43171] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
Traceback (most recent call last):
  File "/Users/mcychen/anaconda/lib/python2.7/site-packages/glue/core/qt/layer_artist_model.py", line 207, in rowsInserted
    parent.on_artist_add(self.model().artists)
  File "/Users/mcychen/anaconda/lib/python2.7/site-packages/glue/core/qt/layer_artist_model.py", line 312, in on_artist_add
    self.layout_style_widgets[layer_artist] = self.layer_style_widget_cls(layer_artist)
  File "/Users/mcychen/anaconda/lib/python2.7/site-packages/glue_vispy_viewers/volume/layer_style_widget.py", line 49, in __init__
    self._update_limits()
  File "/Users/mcychen/anaconda/lib/python2.7/site-packages/glue/external/echo.py", line 268, in __exit__
    p.notify(self.instance, old, new)
  File "/Users/mcychen/anaconda/lib/python2.7/site-packages/glue/external/echo.py", line 87, in notify
    cback(new)
  File "/Users/mcychen/anaconda/lib/python2.7/site-packages/glue/utils/misc.py", line 57, in result
    return func(*args, **kwargs)
  File "/Users/mcychen/anaconda/lib/python2.7/site-packages/glue_vispy_viewers/volume/layer_artist.py", line 153, in _update_data
    self._multivol.set_data(self.id, data)
  File "/Users/mcychen/anaconda/lib/python2.7/site-packages/glue_vispy_viewers/volume/volume_visual_legacy.py", line 215, in set_data
    self._update_scaled_data(label)
  File "/Users/mcychen/anaconda/lib/python2.7/site-packages/glue_vispy_viewers/volume/volume_visual_legacy.py", line 230, in _update_scaled_data
    self._vol_shape = self._data_shape * self._block_size
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
`

**Comment by astrofrog** [comment]
@mcyc - thanks for the report, this is a bug that will be fixed in the next release of the 3D plugin (that I hope to do today)

**Comment by mcyc** [comment]
@astrofrog - excellent. Thanks!

**Comment by astrofrog** [comment]
@mcyc - just to check, are you seeing this issue with the latest version of glue-vispy-viewers? (v0.4)

**Comment by astrofrog** [comment]
@mcyc - I'll close this for now, but please feel free to re-open if you are still having issues!
