### ISSUE TITLE
Fix the current IsoSurface 3D viewer

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue-vispy-viewers#163]
The viewer doesn't work with the error below:

> 2016-06-23 16:42:17.077 python[2252:880522] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
> Traceback (most recent call last):
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/utils/qt/widget_properties.py", line 351, in update_prop
>     setattr(client, prop, val)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/external/echo.py", line 64, in **set**
>     self.notify(instance, old, new)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/external/echo.py", line 87, in notify
>     cback(new)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/utils/misc.py", line 57, in result
>     return func(_args, *_kwargs)
>   File "/Users/penny/Works/Gluedev/glue-3d-viewer/glue_vispy_viewers/isosurface/layer_artist.py", line 83, in _update_color
>     self._iso_visual.color = self._vispy_color
> AttributeError: 'IsosurfaceLayerArtist' object has no attribute '_vispy_color'

**Comment by PennyQ** [comment]
Not happened anymore, I will close it
