### ISSUE TITLE
selection on 3D volume viewer crashed after qtpy change of Glue

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue-vispy-viewers#179]
Error as follow:

> Traceback (most recent call last):
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/utils/misc.py", line 57, in result
>     return func(_args, *_kwargs)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/app/qt/layer_tree_widget.py", line 182, in _do_action
>     self._layer_tree.data_collection.remove_subset_group(s)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/data_collection.py", line 211, in remove_subset_group
>     s.delete()
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/subset.py", line 317, in delete
>     self.data.hub.broadcast(msg)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/hub.py", line 181, in broadcast
>     handler(message)
>   File "/Users/penny/anaconda/lib/python2.7/site-packages/glue_vispy_viewers-0.5.dev0-py2.7.egg/glue_vispy_viewers/common/vispy_data_viewer.py", line 96, in _remove_subset
>     self._layer_artist_container.pop(message.subset)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/layer_artist.py", line 360, in pop
>     self.remove(r)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/qt/layer_artist_model.py", line 353, in remove
>     self.model.removeRow(index)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/utils/qt/python_list_model.py", line 96, in removeRow
>     self._remove_row(row)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/qt/layer_artist_model.py", line 83, in _remove_row
>     art.clear()
>   File "/Users/penny/anaconda/lib/python2.7/site-packages/glue_vispy_viewers-0.5.dev0-py2.7.egg/glue_vispy_viewers/volume/layer_artist.py", line 113, in clear
>     self._multivol.set_data(self.id, np.zeros(self._multivol._data_shape))
>   File "/Users/penny/anaconda/lib/python2.7/site-packages/glue_vispy_viewers-0.5.dev0-py2.7.egg/glue_vispy_viewers/volume/volume_visual.py", line 195, in set_data
>     raise ValueError("set_clim should be called before set_data")
> ValueError: set_clim should be called before set_data

**Comment by PennyQ** [comment]
Seems works now after updates, I will close it.
