### ISSUE TITLE
Selection on 3D volume not work: "AttributeError: 'list' object has no attribute 'uuid'"

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue-vispy-viewers#217]
More info as below:

> WARNING:vispy:Traceback (most recent call last):
>   File "/Users/penny/anaconda/bin/glue", line 11, in <module>
>     load_entry_point('glueviz', 'gui_scripts', 'glue')()
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/main.py", line 232, in main
>     start_glue(**kwargs)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/main.py", line 172, in start_glue
>     return ga.start()
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/app/qt/application.py", line 875, in start
>     return self.app.exec_()
>   File "/Users/penny/Works/Gluedev/glue-3d-viewer/glue_vispy_viewers/extern/vispy/app/backends/_qt.py", line 431, in event
>     out = super(QtBaseCanvasBackend, self).event(ev)
>   File "/Users/penny/Works/Gluedev/glue-3d-viewer/glue_vispy_viewers/extern/vispy/app/backends/_qt.py", line 380, in mouseReleaseEvent
>     modifiers=self._modifiers(ev),
>   File "/Users/penny/Works/Gluedev/glue-3d-viewer/glue_vispy_viewers/extern/vispy/app/base.py", line 216, in _vispy_mouse_release
>     ev = self._vispy_canvas.events.mouse_release(**kwargs)
>   File "/Users/penny/Works/Gluedev/glue-3d-viewer/glue_vispy_viewers/extern/vispy/util/event.py", line 455, in **call**
>     self._invoke_callback(cb, event)
>   File "/Users/penny/Works/Gluedev/glue-3d-viewer/glue_vispy_viewers/extern/vispy/util/event.py", line 475, in _invoke_callback
>     self, cb_event=(cb, event))
>   << caught exception here: >>
>   File "/Users/penny/Works/Gluedev/glue-3d-viewer/glue_vispy_viewers/extern/vispy/util/event.py", line 471, in _invoke_callback
>     cb(event)
>   File "/Users/penny/Works/Gluedev/glue-3d-viewer/glue_vispy_viewers/volume/volume_toolbar.py", line 108, in on_mouse_release
>     self.mark_selected(shape_mask, self.visible_data)
>   File "/Users/penny/Works/Gluedev/glue-3d-viewer/glue_vispy_viewers/common/toolbar.py", line 295, in mark_selected
>     subset_state = ElementSubsetState(indices=np.where(mask)[0], data=visible_data)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/subset.py", line 888, in __init__
>     self._data_uuid = data.uuid
> AttributeError: 'list' object has no attribute 'uuid'

**Comment by PennyQ** [comment]
@astrofrog This is after I updated to the latest dev glue and glue_vispy_viewers
