### ISSUE TITLE
Error: Save the figure in 3D viewer currently default as an empty data type

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue-vispy-viewers#270]
As above, should set the default as 'PNG' or any.

**Comment by PennyQ** [comment]
> Traceback (most recent call last):
  File "/Users/penny/anaconda/envs/glue-dev/lib/python2.7/site-packages/glue/viewers/common/qt/toolbar.py", line 111, in trigger
    self.active_tool = tool
  File "/Users/penny/anaconda/envs/glue-dev/lib/python2.7/site-packages/glue/viewers/common/qt/toolbar.py", line 66, in active_tool
    self.activate_tool(new_tool)
  File "/Users/penny/anaconda/envs/glue-dev/lib/python2.7/site-packages/glue_vispy_viewers/common/toolbar.py", line 27, in activate_tool
    super(VispyViewerToolbar, self).activate_tool(mode)
  File "/Users/penny/anaconda/envs/glue-dev/lib/python2.7/site-packages/glue/viewers/common/qt/toolbar.py", line 84, in activate_tool
    tool.activate()
  File "/Users/penny/anaconda/envs/glue-dev/lib/python2.7/site-packages/glue_vispy_viewers/common/tools.py", line 50, in activate
    file_filter = str(file_filter).split()[0]
IndexError: list index out of range

**Comment by astrofrog** [comment]
@PennyQ - do you have time to look into this to open a pull request?

**Comment by PennyQ** [comment]
@astrofrog Yes sure, I will work on it!

**Comment by astrofrog** [comment]
Closed in #276 - thanks @PennyQ!
