### ISSUE TITLE
glue.core.exceptions.IncompatibleAttribute error 

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue-vispy-viewers#57]
I got this error when trying subset highlight both in 3D volume rendering viewer and 3D scatter plot viewer with most test data (except one molecular cloud catalogue) I have. I am wondering what's the problem with this error. The error information is listed as below for information:

```
Traceback (most recent call last):
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glue/qt/data_collection_model.py", line 323, in setData
    self._get_item(index).label = value
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glue/qt/data_collection_model.py", line 171, in label
    self.subset_group.label = value
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glue/core/subset_group.py", line 178, in __setattr__
    self.broadcast(attr)
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glue/core/subset_group.py", line 173, in broadcast
    s.broadcast(item)
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glue/core/subset.py", line 242, in broadcast
    self.data.hub.broadcast(msg)
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glue/core/hub.py", line 180, in broadcast
    handler(message)
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glue_vispy_viewers-0.2.dev0-py2.7.egg/glue_vispy_viewers/scatter/scat_vispy_viewer.py", line 63, in _update_subset
    self._update_subsets()
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glue_vispy_viewers-0.2.dev0-py2.7.egg/glue_vispy_viewers/scatter/scat_vispy_viewer.py", line 78, in _update_subsets
    'alpha': s.style.alpha} for s in self._subsets if s.to_mask().ndim == 3])
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glue/core/subset.py", line 210, in to_mask
    raise exc
glue.core.exceptions.IncompatibleAttribute: col1
```

**Comment by astrofrog** [comment]
Are you using the latest glue dev version or the latest stable version?

**Comment by PennyQ** [comment]
The dev version (latest from the master branch Github repository)

**Comment by astrofrog** [comment]
I'm going to close this because I think this will no longer be relevant with the changes in #58 - I did see that error briefly and fixed it.
